// This file is autogenerated. Do not modify!

import Foundation

class SwiftConfiguration {

    enum Configuration: String, CaseIterable {
        case Staging
		case Debug
		case Release
		
    }

    enum ConfigurationKey: String, CaseIterable {
        case testBool
		case testString
		case testDate
		case testNumber
		
    }

    // MARK: Shared instance

    static let current = SwiftConfiguration()

    // MARK: Properties

    private let configurationKey = "SwiftConfiguration.currentConfiguration"
    private let configurationPlistFileName = "Configuration.plist"

    let activeConfiguration: Configuration
    private let activeConfigurationDictionary: NSDictionary

    // MARK: Lifecycle

    init(targetConfiguration: Configuration? = nil) {
        let bundle = Bundle(for: SwiftConfiguration.self)
        guard let rawConfiguration = bundle.object(forInfoDictionaryKey: configurationKey) as? String,
            let configurationDictionaryPath = bundle.path(forResource: configurationPlistFileName, ofType: nil),
            let activeConfiguration = targetConfiguration ?? Configuration(rawValue: rawConfiguration),
            let configurationDictionary = NSDictionary(contentsOfFile: configurationDictionaryPath),
            let activeEnvironmentDictionary = configurationDictionary[activeConfiguration.rawValue] as? NSDictionary
            else {
                fatalError("Configuration Error")

        }
        self.activeConfiguration = activeConfiguration
        self.activeConfigurationDictionary = activeEnvironmentDictionary
    }

    // MARK: Methods

    func value<T>(for key: ConfigurationKey) -> T {
        guard let value = activeConfigurationDictionary[key.rawValue] as? T else {
            fatalError("No value satysfying requirements")
        }
        return value
    }

    func isRunning(in configuration: Configuration) -> Bool {
        return activeConfiguration == configuration
    }
}